### ISSUE TITLE
Create PyPi release

### ISSUE THREAD

**Issue by cwschilly** [Pressio/rom-tools-and-workflows#222]
@fnrizzi @eparish1 

The build process for the [demos](https://github.com/Pressio/rom-tools-and-workflows-demos) repo could be simplified if we push a version of `romtools` to [PyPi](https://pypi.org/) (like we did in pressio-linalg, [here](https://github.com/Pressio/pressio-linalg/blob/main/.github/workflows/publish_pypi_package.yaml)).

This would allow users to install the library with:
```sh
pip install romtools
```

 And in the demos repo, we could then list `romtools` in the `build_requirements.txt` file and avoid having to `git clone` this repo.

**Comment by eparish1** [comment]
This would be great, thanks! If you and Francesco can take care of this that's great; if not I'll look into it sometime next week.

**Comment by fnrizzi** [comment]
this is what we used in the CI for pressio-linalg that does not exist anymore, just pasting it here not to lose it.

```
name: Publish Python package to PyPi

on: push

jobs:
  build-and-publish:
    name: Build and publish Python Package to PyPi
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install build
        run: |
          python -m pip install build --user
      - name: Build a binary wheel and a source tarball
        run: |
          python -m build --sdist --wheel --outdir dist/ .
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          verbose: true
          print-hash: true
```
